build:
  version: "1.0"

loans:
  message: "Welcome to Loans services PROD"
  loansInfo:
    name: "John Doe PROD"
    email: "johnprod@gmail.com"
  onCallSupport:
    - (555) 0219 2698
    - (555) 0139 2698