build:
  version: "1.0"

accounts:
  message: "Welcome to Accounts services QA"
  accountsContactInfo:
    name: "John Doe qa"
    email: "johnqa@gmail.com"
  onCallSupport:
    - (555) 0112 2511
    - (555) 0112 2298