server:
  port: 9000
spring:
  application:
    name: "cards"
  profiles:
    active: "qa"
  datasource:
    url: jdbc:h2:mem:carddb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  name: "cards"
  version: "0.0.1"
  description: "Cards applications"

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8070/eureka/